import "./globals.css";
import { DataProvider } from "@/component/globalcontext/DataContext";


import Navigation from "@/component/navigation/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation/>
    
        <DataProvider>
          <div className="body">
            <div>
              {children}
            </div>
            
          </div>
        </DataProvider>
    
     
      </body>
    </html>
  );
}
